### ISSUE TITLE
Docker for CPU Error

### ISSUE THREAD

**Issue by ehsantn** [scanner-research/scanner#118]
I'm using the CPU docker to run the main example but it throws this error:
```
root@7702ff2ac3f6:/opt/scanner# python examples/apps/face_detection/main.py star_wars_heros.mp4
Detecting faces in movie star_wars_heros.mp4
Traceback (most recent call last):
  File "examples/apps/face_detection/main.py", line 18, in <module>
    with Database() as db:
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 178, in __init__
    self.start_cluster(master, workers);
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 416, in start_cluster
    assert res
AssertionError
```

**Comment by apoms** [comment]
We were having some issues with our automated build system which was just fixed. Could you retry the command and let me know if it's working now?

Thanks @ehsantn

**Comment by ehsantn** [comment]
A different error now:
```
root@139c84d8a71a:/opt/scanner# python examples/apps/face_detection/main.py star_wars_heros.mp4
Detecting faces in movie star_wars_heros.mp4
Your Scanner configuration file does not exist. Create one? [Y/n]
Wrote Scanner configuration to /root/.scanner.toml
Traceback (most recent call last):
  File "examples/apps/face_detection/main.py", line 18, in <module>
    with Database() as db:
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 184, in __init__
    self.start_cluster(master, workers);
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 428, in start_cluster
    'port already?)'.format(self.config.master_port))
scannerpy.common.ScannerException: Failed to connect to local master process on port 5001. (Is there another process that is bound to that port already?)
```

**Comment by ehsantn** [comment]
new error:
```
E0109 02:00:41.292443   144 master.cpp:867] Master did not receive heartbeat in 50000ms. Shutting down.
Detecting faces in movie star_wars_heros.mp4
Traceback (most recent call last):
  File "examples/apps/face_detection/main.py", line 18, in <module>
    with Database() as db:
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 222, in __init__
    self.start_cluster(master, workers)
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 474, in start_cluster
    res = self._connect_to_master()
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 371, in _connect_to_master
    self._master.Ping(self.protobufs.Empty())
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 491, in __call__
    credentials)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 485, in _blocking
    _handle_event(completion_queue.poll(), state,
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 99, in grpc._cython.cygrpc.CompletionQueue.poll
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 426, in _handle_signal
    self._stop_heartbeat()
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 420, in _stop_heartbeat
    self._heartbeat_queue.put(0)
AttributeError: 'Database' object has no attribute '_heartbeat_queue'
```

**Comment by jblakley** [comment]
I am also having issues with the CPU docker image. When I run the faces example, it starts but just hangs. Output file attached. 
[outfile.txt](https://github.com/scanner-research/scanner/files/1616601/outfile.txt)
A few days ago it would execute the example but would hang somewhere near the end (seemed like during the final encode) then crash. Sorry don't have  that output file.

**Comment by jblakley** [comment]
Tried with  a native (i.e., non-docker) build of scanner for CPU. Worked fine running the shot example. It hung with faces example -- i.e., after starting, it did nothing for several minutes then crashed with this:

100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:34<00:00,  1.00s/it, workers=1, tasks=0, jobs=1]
E0110 17:01:01.481125  2146 master.cpp:1048] IO packet size (10000) must be a multiple of work packet size (32).
Traceback (most recent call last):
  File "examples/apps/face_detection/main.py", line 28, in <module>
    movie_name + '_bboxes')
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/stdlib/pipelines.py", line 110, in detect_faces
    pipeline_instances_per_node=pipeline_instances)
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 1141, in run
    raise ScannerException(job_status.result.msg)
scannerpy.common.ScannerException: IO packet size (10000) must be a multiple of work packet size (32).

**Comment by kayvonf** [comment]
note to Jim...

Alex Poms is out of the office until tonight, and then we'll be pushing hard on SIGGRAPH for a few days, so bare with us if we're less responsive for the back half of this week.

**Comment by jblakley** [comment]
Kayvon, no worries.

**Comment by willcrichton** [comment]
@jblakley this bug should be fixed now
