### ISSUE TITLE
Failed to load op library: libcaffe.so.1.0.0: undefined symbol : cudnnSetLRNDescriptor

### ISSUE THREAD

**Issue by sth1997** [scanner-research/scanner#229]
When I run the command "python3 examples/apps/quickstart/main.py", it caused an error like this:
Traceback (most recent call last):
  File "examples/apps/quickstart/main.py", line 3, in <module>
    db = Database()
  File "/home/sth/.local/lib/python3.6/site-packages/scannerpy/database.py", line 187, in __init__
    self.start_master(master)
  File "/home/sth/.local/lib/python3.6/site-packages/scannerpy/database.py", line 704, in start_master
    '{}/../scanner/stdlib/stdlib_pb2.py'.format(SCRIPT_DIR))
  File "/home/sth/.local/lib/python3.6/site-packages/scannerpy/database.py", line 534, in load_op
    lambda: self._master.LoadOp(op_path, timeout=self._grpc_timeout))
  File "/home/sth/.local/lib/python3.6/site-packages/scannerpy/database.py", line 368, in _try_rpc
    raise ScannerException(result.msg)
scannerpy.common.ScannerException: Failed to load op library: /home/sth/.local/lib/libcaffe.so.1.0.0: undefined symbol: cudnnSetLRNDescriptor

But /usr/local/cuda-9.0/extras/cudnn-7.0.5/lib64 and /usr/local/cuda-9.0/lib64 are all in my LD_LIBRARY_PATH.
Have you ever seen this error? Do you have any idea?
Let me know if you need more info.

**Comment by sth1997** [comment]
It seems that there is something error when I compiled caffe.
