### ISSUE TITLE
hyperlapse example: Op FeatureExtractor does not exist

### ISSUE THREAD

**Issue by yichunk** [scanner-research/scanner#231]
Hi, I am trying to run the example apps/hyperlapse.

It seems the example  is not using the most updated API? 

[here](https://github.com/scanner-research/scanner/blob/master/examples/apps/hyperlapse/main.py#L37) uses `db.table('example').as_op().range(0, 1000, item_size=100)` as source, but Scanner complains there is no `as_op` attribute for `Table`. Therefore, I change it to  `db.source.FrameColumn()` as QuickStart example.

However, I encounter the following problem

```
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    extract_features()
  File "main.py", line 39, in extract_features
    features, keypoints = db.ops.FeatureExtractor(
  File "/root/.local/lib/python3.5/site-packages/scannerpy/op.py", line 115, in __getattr__
    op_info = self._db._get_op_info(name)
  File "/root/.local/lib/python3.5/site-packages/scannerpy/database.py", line 428, in _get_op_info
    raise ScannerException(op_info.result.msg)
scannerpy.common.ScannerException: Op FeatureExtractor does not exist
```

I am using the latest CPU docker provided by Scanner project.

Could someone check this example? Thanks!

**Comment by apoms** [comment]
@willcrichton Any thoughts here?

**Comment by willcrichton** [comment]
It looks like the example hasn't been updated in a while. When I get the chance I'll modernize it to the latest API.
